/var/www/legal_drop/docker/nginx/logs/*.log {
    daily
    maxsize 100M
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    su legaldrop legaldrop
    create 0644 legaldrop legaldrop
    sharedscripts
    postrotate
        if [ "$(/usr/bin/docker inspect -f '{{.State.Running}}' legal-drop-nginx-development 2>/dev/null)" = true ]; then
            /usr/bin/docker kill --signal=USR1 legal-drop-nginx-development >/dev/null
        fi
    endscript
}
